---
title: "visualization_2"
author: "ruby"
date: "2025-09-30"
output: html_document
---

load library 
```{r}
library(tidyverse)
library(patchwork)
library(p8105.datasets)
```

import weather data
```{r}
data("weather_df")
```

make our basic scatterplot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
  x = "Minimum daily temp",
  y = "Maximum daily temp",
  title = "Temperature scatterplot", 
  caption = "Data from NOAA",
  color = "Location"
)
```

## Scales 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
  x = "Minimum daily temp",
  y = "Maximum daily temp",
  title = "Temperature scatterplot", 
  caption = "Data from NOAA",
  color = "Location"
) +
  scale_x_continuous(
    breaks = c(-20,0,25), 
    labels = c("-20C", "0", "25")
  ) +
 viridis::scale_color_viridis(
    discrete = TRUE
 )
```

## Themes 

Make my base plot. 

```{r}
ggp_temperature = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
  x = "Minimum daily temp",
  y = "Maximum daily temp",
  title = "Temperature scatterplot", 
  caption = "Data from NOAA",
  color = "Location"
) +
  scale_x_continuous(
    breaks = c(-20,0,25), 
    labels = c("-20C", "0", "25")
  ) +
 viridis::scale_color_viridis(
    discrete = TRUE
 )

ggsave("weather_scatterplot.png", ggp_temperature)
```

Update my base plot 

```{r}
ggp_temperature + 
  theme_minimal() +
  theme(legend.position = "bottom") 
   
```

theme_minimal resets everything so order matters here to put the legend at the bottom!

## Adding data to geoms 

```{r}
central_park_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df = 
 weather_df |> 
  filter(name == "Molokai_HI")

ggplot(data = molokai_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)
```

## `patchwork`

Make three plots and combine using patchwork.

```{r}
ggp_tmax_tmin = 
  weather_df |> 
  ggplot(aes(x=tmin, y = tmax, color= name)) +
  geom_point(alpha = 0.5) +
  theme(legend.position = "none")

ggp_prec_density = 
  weather_df |> 
  filter(prcp >0) |> 
  ggplot(aes(x=prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "none")

ggp_temp_season = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name )) +
  geom_point(alpha = 0.5) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prec_density) / ggp_temp_season
```

## Data manipulation 

Let's make temperature violin plots. 

```{r}
weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```

```{r}
weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```


What about data tidiness 

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat")
```

